apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: even-num
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: selector
            template: oparator
          - name: Mono
            depends: selector
            template: Mono
            when: "{{tasks.selector.outputs.result}} == Mono"
          - name: Odd
            depends: selector
            template: Odd
            when: "{{tasks.selector.outputs.result}} == Odd"
      outputs:
        parameters:
          - name: result
            valueFrom:
              expression: "tasks['selector'].outputs.result == 'Mono' ? tasks.Mono.outputs.result : tasks.Odd.outputs.result"
            
    - name: oparator
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          import random
          print("Mono" if random.randint(0,1) == 0 else "Odd")

    - name: Mono
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          food = ["water","coff","tea"]
          for x in food:
            print(x)
          
    - name: Odd
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("Odd")