apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nodejs-nithya
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: hello
  serviceAccountName: argo
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
  templates:
    - name: hello
      dag:
        tasks:
          - name: build-container-image
            templateRef:
              name: container-image
              template: build-kaniko-git
              clusterScope: true
            arguments:
               parameters:
                 - name: app_repo
                   value: git://github.com/NithyaParavasthu/nodejs-welcome.git
                 - name: container_image
                   value: nithyap04/kaniko
                 - name: container_tag
                   value: "1.3.0"
