apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: nodejs-welcome
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: nodejs-nithya
                namespace: argo
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
              spec:
                entrypoint: hello
                serviceAccountName: argo
                volumes:
                 - name: kaniko-secret
                   secret:
                     secretName: regcred
                     items:
                      - key: .dockerconfigjson
                        path: config.json
                templates:
                 - name: hello
                   dag:
                     tasks:
                      - name: build-container-image
                        templateRef:
                          name: container-image
                          template: build-kaniko-git
                          clusterScope: true
                        arguments:
                          parameters:
                           - name: app_repo
                             value: git://github.com/NithyaParavasthu/nodejs-welcome.git
                           - name: container_image
                             value: nithyap04/kaniko
                           - name: container_tag
                             value: "1.6.0"