apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  selector:
    eventsource-name: github
  github:
    nodejs-welcome:
      repositories:
        - owner: NithyaParavasthu
          names:
            - Argo
            - nodejs-welcome
      webhook:
        endpoint: /nodejs-welcome
        port: "12000"
        method: POST
        url: http://8.tcp.ngrok.io:19986
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
