apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    nodejs-welcome:
      repositories:
        - owner: NithyaParavasthu
          names:
            - Argo
            - nodejs-welcome
      webhook:
        endpoint: /nodejs-welcome
        port: "12000"
        method: POST
        url: https://80e9-183-82-115-199.ngrok.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
