apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/NithyaParavasthu
          name: NithyaParavasthu
        - mountPath: /secret
          name: sshkey
        - mountPath: /etc/ssh
          name: known-hosts
    volumes:
      - name: NithyaParavasthu
        emptyDir: {}
      - name: sshkey
        secret:
          secretName: git-ssh
      - name: known-hosts
        secret:
          secretName: git-known-hosts
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: nodejs-welcome
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "git@github.com:NithyaParavasthu/Argo.git"
              cloneDirectory: "/git/argo"
              sshKeyPath: "/secret/key"
              namespace: argo-events
              filePath: "argo-workflow/kaniko-workflow.yaml"
              branch: "master"