apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    eventsource-name: github
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-eventsource
spec:
  ports:
  - port: 13000
    protocol: TCP
    targetPort: 13000
  selector:
    eventsource-name: gitlab
  type: NodePort