apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
        - cluster: engg-prod
          url: https://vc-kua0c3dxklmufa8spn2h.apps.aws-mumbai-eks.klusternetes.com
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 9.7.5
        helm: 
          releaseName: nginx
      destination:
        server: '{{url}}'
        namespace: default
